# fly.toml app configuration file generated for callvault-api on 2024-03-10T16:00:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'elysiajs-api-starter'
primary_region = 'jnb'

[build]

[deploy]
strategy = 'bluegreen'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'requests'
hard_limit = 250
soft_limit = 200

[[http_service.checks]]
interval = '30s'
timeout = '5s'
grace_period = '10s'
method = 'GET'
path = '/api/v1/health'

[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 2
